apiVersion: v1
kind: Service
metadata:
  name: credit-scoring
  namespace: ledgerx
  labels: { app.kubernetes.io/name: credit-scoring, ledgerx.io/domain: lending }
spec:
  type: ClusterIP
  ports: [{ name: http, port: 50102, targetPort: 50102 }]
  selector: { app.kubernetes.io/name: credit-scoring }
