apiVersion: v1
kind: Namespace
metadata:
  name: ledgerx
  labels:
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: cards-cde
  labels:
    pod-security.kubernetes.io/enforce: restricted
    istio-injection: enabled
    ledgerx.io/pci-dss-scope: "true"
---
apiVersion: v1
kind: Namespace
metadata: { name: ledgerx-data, labels: { pod-security.kubernetes.io/enforce: restricted, istio-injection: enabled } }
---
apiVersion: v1
kind: Namespace
metadata: { name: messaging, labels: { pod-security.kubernetes.io/enforce: restricted } }
---
apiVersion: v1
kind: Namespace
metadata: { name: observability, labels: { pod-security.kubernetes.io/enforce: restricted } }
---
apiVersion: v1
kind: Namespace
metadata: { name: security, labels: { pod-security.kubernetes.io/enforce: restricted } }
