spring.application.name=account-service
server.port=${PORT:60020}
management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.probes.enabled=true
spring.datasource.url=jdbc:postgresql://${COCKROACH_HOST:localhost}:${COCKROACH_PORT:26257}/${COCKROACH_DB:ledgerx_ledger}?sslmode=disable
spring.datasource.username=${COCKROACH_USER:ledgerx}
spring.jpa.hibernate.ddl-auto=validate
