apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  namespace: ledgerx
  labels: { app.kubernetes.io/name: gateway-service, ledgerx.io/domain: payments }
spec:
  type: ClusterIP
  ports: [{ name: http, port: 50060, targetPort: 50060 }]
  selector: { app.kubernetes.io/name: gateway-service }
