apiVersion: v1
kind: ConfigMap
metadata:
  name: portfolio-service
  namespace: ledgerx
  labels: { app.kubernetes.io/name: portfolio-service, ledgerx.io/domain: wealth }
data:
  LOG_LEVEL: info
  PORT: "50160"
