apiVersion: v1
kind: ConfigMap
metadata:
  name: collections-service
  namespace: ledgerx
  labels: { app.kubernetes.io/name: collections-service, ledgerx.io/domain: lending }
data:
  LOG_LEVEL: info
  PORT: "50104"
