apiVersion: v1
kind: ConfigMap
metadata:
  name: claims-service
  namespace: ledgerx
  labels: { app.kubernetes.io/name: claims-service, ledgerx.io/domain: insurance }
data:
  LOG_LEVEL: info
  PORT: "50181"
