apiVersion: v1
kind: Service
metadata:
  name: claims-service
  namespace: ledgerx
  labels: { app.kubernetes.io/name: claims-service, ledgerx.io/domain: insurance }
spec:
  type: ClusterIP
  ports: [{ name: http, port: 50181, targetPort: 50181 }]
  selector: { app.kubernetes.io/name: claims-service }
