apiVersion: v1
kind: ConfigMap
metadata:
  name: underwriting-service
  namespace: ledgerx
  labels: { app.kubernetes.io/name: underwriting-service, ledgerx.io/domain: lending }
data:
  LOG_LEVEL: info
  PORT: "50101"
