apiVersion: v1
kind: ConfigMap
metadata:
  name: relationship-service
  namespace: ledgerx
  labels: { app.kubernetes.io/name: relationship-service, ledgerx.io/domain: customer-360 }
data:
  LOG_LEVEL: info
  PORT: "50281"
