apiVersion: v1
kind: ConfigMap
metadata:
  name: router-service
  namespace: ledgerx
  labels: { app.kubernetes.io/name: router-service, ledgerx.io/domain: payments }
data:
  LOG_LEVEL: info
  PORT: "50061"
