apiVersion: v1
kind: Service
metadata:
  name: router-service
  namespace: ledgerx
  labels: { app.kubernetes.io/name: router-service, ledgerx.io/domain: payments }
spec:
  type: ClusterIP
  ports: [{ name: http, port: 50061, targetPort: 50061 }]
  selector: { app.kubernetes.io/name: router-service }
