apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ledgerx-app-of-apps
  namespace: argocd
  finalizers: [resources-finalizer.argocd.argoproj.io]
spec:
  project: ledgerx
  source:
    repoURL: https://github.com/prabhat-roy/LedgerX
    targetRevision: HEAD
    path: gitops/argocd/applicationsets
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions: [CreateNamespace=true]
