apiVersion: v1
kind: Service
metadata:
  name: reconciliation-service
  namespace: ledgerx
  labels: { app.kubernetes.io/name: reconciliation-service, ledgerx.io/domain: reconciliation }
spec:
  type: ClusterIP
  ports: [{ name: http, port: 50320, targetPort: 50320 }]
  selector: { app.kubernetes.io/name: reconciliation-service }
